### ISSUE TITLE
Add more metadata to the output

### ISSUE THREAD

**Issue by ostasevych** [callmemagnus/nextcloud-searchpage#6]
I found that your app is quite nice. Would that be possible to add more metadata to the results of the output, where present in the files eg:
- Date Modified
- Size
- Authors
- File type

eg, Windows Search gives these ones:
![image](https://github.com/callmemagnus/nextcloud-searchpage/assets/5199030/1b9d1585-72a6-47e3-ae20-457bc684c0e4)

Plus, add a bit more space and/or dividers between each item, make them not so wide on the screen.

**Comment by callmemagnus** [comment]
I would like to but currently, the application is using the responses from Nextcloud's search.

In a nutshell:

1. a data application declares a provider
2. nextcloud exposes that via its API
3. when a request comes, it uses the implementation in the data application
4. the contract of that response is "standard" and does not contain any metadata :-(

I don't think there is a standardized way to get meta data from data application.

I'm afraid to have to add the support per application which brings huge issues for maintenance.

**Comment by ostasevych** [comment]
> I would like to but currently, the application is using the responses from Nextcloud's search.
> 
> In a nutshell:
> 
> 1. a data application declares a provider
> 2. nextcloud exposes that via its API
> 3. when a request comes, it uses the implementation in the data application
> 4. the contract of that response is "standard" and does not contain any metadata :-(
> 
> I don't think there is a standardized way to get meta data from data application.
> 
> I'm afraid to have to add the support per application which brings huge issues for maintenance.

I understand that the NC devs coded to show only primitive search output. Perhaps, it is possible to use queries with some attributes to get extended data? If not, would you mind to submit proper feature request, which will be helpful for your app?

**Comment by callmemagnus** [comment]
As long as the metadata are fetched through an API provided by Nextcloud (not a specific application). I'm happy to get PRs.

I don't think the search API provides anything fancy. Probably because it wouldn't apply to all applications.

I would hope those APIs to become better and that the search implementation in applications becomes better (e.g. for most providers, a two word search is using OR although I would have expected it to be AND).

I don't want to get the maintenance hell that would come from using other's application APIs to fetch data as there will be no real contract with those API as their consumer is usually its own front-end and because of that there will hard to track changes on other application's API.

Hence, my above comment about using officially provided API that have proper release cycles.
